default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>
  socket: /tmp/mysql.sock
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  # strict: false
  # strict_mode: false
  idle_timeout: 600
  timeout: 300000

  # aurora failever 대응. mysql2-aurora gem config
  reconnect: true
  aurora_max_retry: 5

development:
  <<: *default
  database: ihavecat
  # 개발DB
  host: <%= Rails.application.credentials.dig(('development').to_sym, :database, :host) %>
  port: <%= Rails.application.credentials.dig(('development').to_sym, :database, :port) %>
  username: root

dev:
  <<: *default
  database: ihavecat
  # 개발DB
  host: <%= Rails.application.credentials.dig(('development').to_sym, :database, :host) %>
  port: <%= Rails.application.credentials.dig(('development').to_sym, :database, :port) %>
  username: <%= Rails.application.credentials.dig(('development').to_sym, :database, :user) %>
  password: <%= Rails.application.credentials.dig(('development').to_sym, :database, :password) %>

test:
  <<: *default
  database:

production:
  <<: *default
  database:
